server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true

spring:
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50

    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

    defer-datasource-initialization: true

  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLE}
      path: /h2-console